# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_id', models.CharField(max_length=70, unique=True, verbose_name=b'\xe4\xbc\x81\xe4\xb8\x9a\xe5\x8f\xb7ID')),
                ('wechat_agent_id', models.IntegerField(verbose_name=b'anent id')),
                ('wechat_key', models.CharField(max_length=128, verbose_name=b'\xe4\xbc\x81\xe4\xb8\x9a\xe5\x8f\xb7KEY')),
            ],
            options={
                'verbose_name_plural': '\u5fae\u4fe1\u4f01\u4e1a\u53f7\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Wechat_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u5fae\u4fe1\u65e5\u5fd7',
            },
        ),
        migrations.AddField(
            model_name='cmsuser',
            name='wechat_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name=b'\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8f\xb7'),
        ),
    ]
